/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.HiloDijkstra;
import control.HiloFloydWarshall;
import control.IGraph;
import modelo.Dijkstra;
import modelo.Floyd_Warshall;
import modelo.Graph;
import modelo.retornarGrafos;

/**
 *
 * @author Portatil1
 */
public class ventana extends javax.swing.JFrame {
    control.HiloDijkstra dijkstraGo;
    control.HiloFloydWarshall floydGo;
    modelo.retornarGrafos grafoD = new retornarGrafos();
    modelo.retornarGrafos grafoD1 = new retornarGrafos();
    public static String reporDis;
    public static String reporFloyd;
    public static Long tD;
    public static Long tF;
    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
//    private void reporFinal(){
//        if (t) {
//            
//        }
//    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grafo4 = new javax.swing.JButton();
        grafo5 = new javax.swing.JButton();
        grafo1 = new javax.swing.JButton();
        grafo2 = new javax.swing.JButton();
        grafo3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        espDijkstra = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        espFloyd = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dijkstra - VS - Floyd Warsall");

        grafo4.setText("Grafo 4");
        grafo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grafo4ActionPerformed(evt);
            }
        });

        grafo5.setText("Grafo 5");
        grafo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grafo5ActionPerformed(evt);
            }
        });

        grafo1.setText("Grafo 1");
        grafo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grafo1ActionPerformed(evt);
            }
        });

        grafo2.setText("Grafo 2");
        grafo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grafo2ActionPerformed(evt);
            }
        });

        grafo3.setText("Grafo 3");
        grafo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grafo3ActionPerformed(evt);
            }
        });

        espDijkstra.setEditable(false);
        espDijkstra.setColumns(20);
        espDijkstra.setRows(5);
        jScrollPane1.setViewportView(espDijkstra);

        espFloyd.setEditable(false);
        espFloyd.setColumns(20);
        espFloyd.setRows(5);
        jScrollPane2.setViewportView(espFloyd);

        resultado.setEditable(false);
        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane3.setViewportView(resultado);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("El siguiente programa tiene disponibles 5 grafos diferentes para probar la eficacia de ambos algoritmos.");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grafo1)
                        .addGap(100, 100, 100)
                        .addComponent(grafo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(grafo3)
                        .addGap(125, 125, 125)
                        .addComponent(grafo4)
                        .addGap(99, 99, 99)
                        .addComponent(grafo5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grafo4)
                    .addComponent(grafo5)
                    .addComponent(grafo3)
                    .addComponent(grafo2)
                    .addComponent(grafo1))
                .addContainerGap())
        );

        grafo2.getAccessibleContext().setAccessibleName("Grafo2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void grafo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grafo1ActionPerformed
        // TODO add your handling code here:
        dijkstraGo = new HiloDijkstra(grafoD.obtenerGrafo1());
        floydGo = new HiloFloydWarshall(grafoD1.obtenerGrafo1());
        dijkstraGo.start();
        floydGo.start();
        espDijkstra.setText(reporDis);
        System.out.println(dijkstraGo.getReporte());
        espFloyd.setText(reporFloyd);
        
    }//GEN-LAST:event_grafo1ActionPerformed

    private void grafo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grafo2ActionPerformed
        // TODO add your handling code here:
        dijkstraGo = new HiloDijkstra(grafoD.obtenerGrafo2());
        floydGo = new HiloFloydWarshall(grafoD1.obtenerGrafo2());
        dijkstraGo.start();
        floydGo.start();
        espDijkstra.setText(reporDis);
        System.out.println(dijkstraGo.getReporte());
        espFloyd.setText(reporFloyd);
    }//GEN-LAST:event_grafo2ActionPerformed

    private void grafo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grafo3ActionPerformed
        // TODO add your handling code here:
        dijkstraGo = new HiloDijkstra(grafoD.obtenerGrafo3());
        floydGo = new HiloFloydWarshall(grafoD1.obtenerGrafo3());
        dijkstraGo.start();
        floydGo.start();
        espDijkstra.setText(reporDis);
        System.out.println(dijkstraGo.getReporte());
        espFloyd.setText(reporFloyd);
    }//GEN-LAST:event_grafo3ActionPerformed

    private void grafo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grafo4ActionPerformed
        // TODO add your handling code here:
        dijkstraGo = new HiloDijkstra(grafoD.obtenerGrafo4());
        floydGo = new HiloFloydWarshall(grafoD1.obtenerGrafo4());
        dijkstraGo.start();
        floydGo.start();
        espDijkstra.setText(reporDis);
        System.out.println(dijkstraGo.getReporte());
        espFloyd.setText(reporFloyd);
    }//GEN-LAST:event_grafo4ActionPerformed

    private void grafo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grafo5ActionPerformed
        // TODO add your handling code here:
        dijkstraGo = new HiloDijkstra(grafoD.obtenerGrafo5());
        floydGo = new HiloFloydWarshall(grafoD1.obtenerGrafo5());
        dijkstraGo.start();
        floydGo.start();
        espDijkstra.setText(reporDis);
        System.out.println(dijkstraGo.getReporte());
        espFloyd.setText(reporFloyd);
    }//GEN-LAST:event_grafo5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea espDijkstra;
    private javax.swing.JTextArea espFloyd;
    private javax.swing.JButton grafo1;
    private javax.swing.JButton grafo2;
    private javax.swing.JButton grafo3;
    private javax.swing.JButton grafo4;
    private javax.swing.JButton grafo5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
